### ISSUE TITLE
samtools v1.11 compatibility?

### ISSUE THREAD

**Issue by jpsmith5** [databio/pepatac#155]
Hey @josruirod, could you share the error you experienced with samtools v1.11? I have successfully run some test cases through with the updated samtools and didn't experience an error.  I'm running some more cases through now, but just curious if you could point out what it is you saw.

_Originally posted by @jpsmith5 in https://github.com/databio/pepatac/issue_comments/705631368_

**Comment by josruirod** [comment]
Hi

Sure, it was when I ran the example, in the bowtie command that is then piping into samtools, there is a samtools sort with the parameter -T. It was giving an error that -T was not recognized and apparently it keep working, but I killed it after couple of hours because it was taking too long and the instructions mentioned less time.
Same conditions, after changing samtools version to 1.10 work perfectly and faster. 
I don't have the log anymore, but I can try to reproduce if it helps.

Thanks for the developing!

**Comment by jpsmith5** [comment]
Okay, great. I'll look specifically at that step. Don't worry about reproducing at the moment, but I may reach back out to you if I can't identify the issue.

**Comment by jpsmith5** [comment]
Well @josruirod, if you have the flexibility and time to see if you can reproduce those errors that'd be great. It's been working across multiple samples and settings for me without any messages regarding the `-T` parameter. Samtools sort itself also still shows a `-T` as one of the possible parameters so I'm admittedly confused.

**Comment by josruirod** [comment]
HI
I'm sorry, but indeed everything is working also with samtools 1.11. I must have confused something, my guess is that I usually manage other older versions of samtools and I may have confused my PATH. I'm sorry for the confussion! But I can also confirm with samtools 1.11 everything is working. 

Please accept my apologies and thanks agian for the support

**Comment by jpsmith5** [comment]
No problem. Just wanted to make sure we figured that out. Thanks for working with me.
