### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by trn30** [databio/pepatac#160]
I have several doubts regarding the pipeline, so I will explain them in a list.
1. Which is the reason to use in Bowtie2 the BED format and the approximation --shift -75 --extsize 150, instead of BEDPE which is specific to paired end samples?
2. When NFRs, di, tri and poly nucleosomes are extracted, then are these files not used later to perform the following steps? if not, could it be done?

Thanks and sorry for the inconvenience.
Regards.

**Comment by jpsmith5** [comment]
Hi @trn30,

1. Regarding `bowtie2`, it is piping output through `samtools` and generating `BAM` formatted files. I think you're referencing the input to `MACS2` that is produced after shifting reads?  Because the pipeline has always handled both SE and PE input, this is a carryover both from that support and as the most broadly adopted usage in our and collaborators hands.  But you're right that this could be informative for paired-end samples. I'll look into either adjusting the default for PE samples to utilize the `BEDPE` format or provide an option to do so.
2. Currently, they are provided as is for user defined purposes and are not the input for downstream steps. These are a recent addition to the pipeline output that I felt could provide downstream utility, but weren't quite up to the universal every run sort of analyses the pipeline is designed to provide. But, yes they could be utilized in a more direct manner. Did you have some specific ideas for the sorts of additional data you'd like to see provided from these files? I'm more than happy to include such things should there be both demand and justification for the additional time and computational demands such steps would require.

No inconvenience at all. Let me know how I can help!
