### ISSUE TITLE
Are fixed peaks defined relative to peak center or summit?

### ISSUE THREAD

**Issue by kwcurrin** [databio/pepatac#177]
Hello,

The awk command in pepatac.py that generates fixed peaks appears to use peak centers. There are both comments refering to peak centers and peak summits. Are the peak centers used? If so, could functionality be added to make fixed peaks from peaks generated from other peak callers besides MACS2? MACS2 should only be needed for fixed peaks if summits are required, not if peak centers are used.

Thanks!

Kevin

**Comment by jpsmith5** [comment]
Hey Kevin,

That's a good observation.  We could extend using centers to other peak callers as opposed to peak summits. I will actually adjust the current approach to reutilize summits instead of centers for MACS2 and compare how distinct the two approaches are, and then extend center use to additional peak callers and try to get a feel for how this affects downstream analyses.

Thanks for the thoughts and spotting the distinction.

**Comment by kwcurrin** [comment]
Hey Jason,

Awesome, thanks for looking into this! 

Kevin
