### ISSUE TITLE
Issues with Result Aggregation in looper runp and looper report！

### ISSUE THREAD

**Issue by zhongzheng1999** [databio/pepatac#272]
Hello, I've encountered some puzzling issues while using PEPATAC and would appreciate any help or insights.

Issues Encountered during PEPATAC Pipeline Tutorial Step-by-Step Guide：
https://pepatac.databio.org/en/latest/tutorial/

Despite successfully obtaining Peak Calling results, I've encountered a perplexing situation. After sequentially running `looper run`, `looper runp`, and `looper report`, I noticed the emergence of a folder named `default_project_record_identifier` in the `result_pipeline` directory, containing only an empty `stat.yaml` file. The appearance of this folder seems unexpected, and I'm unsure if anyone can provide an explanation or guidance.

Additionally, upon running `looper report`, an `index.html` file was generated. However, I observed that within this HTML file, the `summary` is also displayed as a sample. This has left me somewhat perplexed, and I'm uncertain whether this is intended behavior or if I might have encountered a specific issue. I would appreciate any explanations or solutions regarding this phenomenon.

If anyone has experience or insights into these issues, please feel free to share your thoughts. Thank you!

**Comment by donaldcampbelljr** [comment]
Hi, Thank you for posting your concerns.

1. The folder `default_project_record_identifier` is produced upon running `looper runp`. It can be safely ignored. This is a workaround with Looper when running project-level pipelines. I've opened an issue regarding it so that we can implement this functionality more gracefully in the future: https://github.com/pepkit/looper/issues/471

2. `summary` is a project-level record identifier that is used for reporting project-level results. We are currently intentionally displaying `summary` in the report table along with the samples, but we plan to only show sample-level records in the future: https://github.com/pepkit/pipestat/issues/150
