### ISSUE TITLE
docs links in to tutorial leads to 404 errors

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#78]
these links are file not found: 

http://code.databio.org/PEPATAC/tutorial/#31-browse-the-output-directory

**Comment by jpsmith5** [comment]
Fixed in databio/code.databio.org@6cf85f2.  

This is an instance I still haven't fully wrapped my head around where I'm missing these broken links.  When I serve the site from the `PEPATAC` docs the links all work, but in the transfer to `code.databio.org` they're broken.  Do you have a good technique for me to better catch these scenarios?
